### ISSUE TITLE
AI number change to 0 on their map markers

### ISSUE THREAD

**Issue by Blind-Firepower** [luggage66/BECTI-ZERTY-RHS.Altis#11]
This looks like maybe either a Zerty, or a BI thing?  I'm guessing the later, because the former probably would have fixed it already.

**Comment by luggage66** [comment]
No idea where to begin with this. Also it only starts later int he game so I'd need to debug while playing (after identifying what to even check for). Don't hold your breath.

**Comment by Blind-Firepower** [comment]
Fixed by BI in 1.46
