### ISSUE TITLE
Independent salvager doesn't work, and more importantly, hangs factory.

### ISSUE THREAD

**Issue by Blind-Firepower** [luggage66/BECTI-ZERTY-RHS.Altis#17]
I'll check on Zerty's as well.

**Comment by Blind-Firepower** [comment]
Replicated in Zerty-Master branch.  Are we missing a server setting?  Might be worth trying on JMW's online server to see if it's something server-side, but it doesn't look like it's an RHS issue.  Can you look at the code Pal, see if it's something semi-obvious?

**Comment by zerty** [comment]
Haven't try this for ages, ill check when i got the time

**Comment by Blind-Firepower** [comment]
Thanks Zerty, any help would be much appreciated!

**Comment by luggage66** [comment]
@zerty Thanks.
@Blind-Firepower I'll merge this today.
