### ISSUE TITLE
Distinguish MHQ

### ISSUE THREAD

**Issue by luggage66** [luggage66/BECTI-ZERTY-RHS.Altis#5]
- Change vehicle to something atypical?
- Maybe give it a custom name? https://community.bistudio.com/wiki/setVehicleVarName

**Comment by Blind-Firepower** [comment]
Could just use a stock Arma vehicle too.  Marshall?  Bobcat?  :P

**Comment by Blind-Firepower** [comment]
I found an armed RG33 as well

**Comment by Blind-Firepower** [comment]
Ok, I've added the armed RG-33 to the factory (desert variant, the woodland one is unfinished).  The M113 is a PITA to drive anyway unless turned out, so I've left that as HQ and pulled it from the factory list.  The HQ is now the only M113.  Unless I see objections, I'll close this one.
